### ISSUE TITLE
Crashing with Leaflet v1.1.0

### ISSUE THREAD

**Issue by ogix** [danwild/leaflet-velocity#13] opened 2017-06-28 13:47 UTC
After updating to leaflet v1.1.0 I get this error in console: 
```
Cannot assign to read only property 'setTransform' of object '#<Object>'
    at Object.L.Control.Coordinates.L.Control.extend.options.position
```
There is a `setTransform ` function defined to work on leaflet v0.7.x and if I remove it then it works. Is there a quick fix for that without dropping v0.7.x support?

**Comment by chriswilley** [comment] 2017-06-28 17:36
@ogix I discovered this same issue when I upgraded to 1.1.0 of Leaflet. As I do not need to support Leaflet 0.7.x, my solution was to comment out the following section at the top of the source file L.CanvasLayer.js:

```
L.DomUtil.setTransform = L.DomUtil.setTransform || function (el, offset, scale) {
    var pos = offset || new L.Point(0, 0);

    el.style[L.DomUtil.TRANSFORM] =
	(L.Browser.ie3d ?
	'translate(' + pos.x + 'px,' + pos.y + 'px)' :
	'translate3d(' + pos.x + 'px,' + pos.y + 'px,0)') +
	(scale ? ' scale(' + scale + ')' : '');
};
```

and then run "gulp scripts" to re-concatenate the JavaScript modules.

The developer included a _setTransform function in L.CanvasLayer.js that is a duplicate of the above section. As the only reference to setTransform occurs in the _animateZoom function in the same module, you might try adding the following exception catch:

```
_animateZoom: function _animateZoom(e) {
    var scale = this._map.getZoomScale(e.zoom);
    // -- different calc of offset in leaflet 1.0.0 and 0.0.7 thanks for 1.0.0-rc2 calc @jduggan1
    var offset = L.Layer ? this._map._latLngToNewLayerPoint(this._map.getBounds().getNorthWest(), e.zoom, e.center) : this._map._getCenterOffset(e.center)._multiplyBy(-scale).subtract(this._map._getMapPanePos());

    try {
        L.DomUtil.setTransform(this._canvas, offset, scale);
    }
    catch (err) {
        this._setTransform(this._canvas, offset. scale);
    }
}
```

I have no way of testing this to see if it allows Leaflet 0.7.x to work, but my own fix above at least got this plugin working in my setup. Hope this helps.

**Comment by chriswilley** [comment] 2017-06-28 17:52
Also see [this discussion](https://github.com/Leaflet/Leaflet/issues/5589) on Leaflet's GitHub repo. It appears that they want plugins to use their own namespaces rather than altering the L namespace. This supports using the _setTransform function approach, I think.

**Closed** 2017-07-03 23:21 UTC
